# Generated by Django 2.0.3 on 2018-09-16 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='RecordTag',
        ),
    ]
    atomic = False
