# Generated by Django 2.1.2 on 2018-11-21 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rlc',
            name='rlc_members',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rlc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rlc_members', to='api.Rlc'),
        ),
    ]
