# Generated by Django 2.0.3 on 2018-09-16 13:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20180916_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanViewRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('note', models.TextField(max_length=4096, null=True)),
                ('phone_number', models.CharField(default=None, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: Up to 15 digits allowed.', regex='^\\+{0,2}\\d{9,15}$')])),
                ('birthday', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OriginCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('state', models.CharField(choices=[('st', 'safe third country'), ('ot', 'other third country'), ('so', 'safe country')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now_add=True)),
                ('first_contact_date', models.DateField(default=None, null=True)),
                ('last_contact_date', models.DateTimeField(default=None, null=True)),
                ('record_token', models.CharField(max_length=50, unique=True)),
                ('note', models.CharField(max_length=4096)),
                ('state', models.CharField(choices=[('op', 'open'), ('cl', 'closed'), ('wa', 'waiting')], max_length=2)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='recordmanagement.Client')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records_created', to=settings.AUTH_USER_MODEL)),
                ('from_rlc', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_from_rlc', to='api.Rlc')),
            ],
        ),
        migrations.CreateModel(
            name='RecordTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='tagged',
            field=models.ManyToManyField(blank=True, related_name='tagged', to='recordmanagement.RecordTag'),
        ),
        migrations.AddField(
            model_name='record',
            name='working_on_record',
            field=models.ManyToManyField(blank=True, related_name='working_on_record', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='origin_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='recordmanagement.OriginCountry'),
        ),
    ]
