# Generated by Django 2.0.3 on 2018-09-27 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordmanagement', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CanViewRecord',
        ),
    ]
