# Generated by Django 2.1.2 on 2018-11-12 15:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recordmanagement', '0002_delete_canviewrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.BigIntegerField()),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_documents_created', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_documents', to='recordmanagement.Record')),
            ],
        ),
        migrations.CreateModel(
            name='RecordDocumentTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(default=None, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: Up to 15 digits allowed.', regex='^\\+{0,2}\\d{9,15}$')]),
        ),
    ]
