# Generated by Django 2.1.2 on 2018-11-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordmanagement', '0003_auto_20181112_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorddocument',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
