# Generated by Django 2.1.2 on 2018-11-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordmanagement', '0004_auto_20181120_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorddocument',
            name='tagged',
            field=models.ManyToManyField(blank=True, related_name='tagged', to='recordmanagement.RecordDocumentTag'),
        ),
    ]
