# Generated by Django 2.1.2 on 2018-11-23 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordmanagement', '0006_recordmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorddocument',
            name='record',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record_documents', to='recordmanagement.Record'),
        ),
        migrations.AlterField(
            model_name='recordmessage',
            name='record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record_messages', to='recordmanagement.Record'),
        ),
    ]
