# Generated by Django 2.1.2 on 2018-12-04 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recordmanagement', '0007_auto_20181123_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordPermissionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested', models.DateTimeField(auto_now_add=True)),
                ('permitted_on', models.DateTimeField()),
                ('can_edit', models.BooleanField(default=False)),
                ('state', models.CharField(choices=[('re', 'requested'), ('gr', 'granted'), ('de', 'declined')], default='re', max_length=2)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions_requested', to='recordmanagement.Record')),
                ('request_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_permissions_requested', to=settings.AUTH_USER_MODEL)),
                ('request_granted', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_permissions_granted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
