# Generated by Django 2.1.2 on 2018-12-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordmanagement', '0008_recordpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordpermission',
            name='permitted_on',
            field=models.DateTimeField(null=True),
        ),
    ]
